server:
  port: 8080

spring:
  application:
    name: Trip4HaNoi-BE
  
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    time-zone: Asia/Ho_Chi_Minh
  
  profiles:
    active: "@spring.profiles.active@"
#     active: dev

# Cấu hình chung cho tất cả các môi trường
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    web: info
    com.trip4hanoi.app: debug
